substitutions:
  name: btproxy
  friendly_name: Bluetooth Proxy

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: apeeters.btproxy
    version: "1.0"

esp32:
  board: wemos_d1_mini32

dashboard_import:
  package_import_url: github://apeeters/esphome-firmware/btproxy/btproxy.yaml

wifi:
  ap:

api:

logger:

ota:
  - platform: esphome

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic
